### PR TITLE
Add commit

### LINKED ISSUE #18: Adding commit1 index.html file

### PR DESCRIPTION
**Pull request by Srish2712**

### CODE REVIEW

**Comment by specter25** [comment]
@Chia2712 you haven't created a issue and linked your pr with it

**Comment by Srish2712** [comment]
So how should I go about it now?

**Comment by specter25** [comment]
@Chia2712 create a issue and link it now .

**Comment by Srish2712** [comment]
I have created the issue but I can not understand how to link it?

**Comment by specter25** [comment]
okay no issues i will do it @Chia2712

**Pull request merged**
